import { Shop, Offer, Mall } from '../types';
import { MALL_CONFIG } from '../utils/constants';

// Mock data for development - will be replaced with database in future sprints
export const mockMall: Mall = {
  id: MALL_CONFIG.DEFAULT_MALL_ID,
  name: MALL_CONFIG.DEFAULT_MALL_NAME,
  nameAr: MALL_CONFIG.DEFAULT_MALL_NAME_AR,
  description: 'Premium shopping destination in Riyadh',
  address: 'King Fahd Road, Riyadh',
  city: 'Riyadh',
  country: 'Saudi Arabia',
  latitude: 24.7136,
  longitude: 46.6753,
  phone: '+966 11 123 4567',
  email: 'info@riyadhpark.com',
  website: 'https://riyadhpark.com',
  hours: {
    monday: { open: '10:00', close: '22:00', isClosed: false },
    tuesday: { open: '10:00', close: '22:00', isClosed: false },
    wednesday: { open: '10:00', close: '22:00', isClosed: false },
    thursday: { open: '10:00', close: '22:00', isClosed: false },
    friday: { open: '14:00', close: '23:00', isClosed: false },
    saturday: { open: '10:00', close: '23:00', isClosed: false },
    sunday: { open: '10:00', close: '22:00', isClosed: false },
  },
  isActive: true,
  createdAt: new Date('2024-01-01'),
  updatedAt: new Date(),
};

export const mockShops: Shop[] = [
  {
    id: 'shop-001',
    mallId: MALL_CONFIG.DEFAULT_MALL_ID,
    name: 'Adidas',
    nameAr: 'أديداس',
    category: 'Fashion',
    iconUrl: 'https://example.com/icons/adidas.png',
    websiteUrl: 'https://adidas.com',
    description: 'Global sports brand offering athletic footwear, apparel, and accessories',
    location: { floor: '1', zone: 'A', unit: '101' },
    contact: { phone: '+966 11 111 1111', whatsapp: '+966 50 111 1111', email: 'adidas@riyadhpark.com' },
    hours: mockMall.hours,
    rating: 4.5,
    isActive: true,
    subscription: { tier: 'premium', status: 'active' },
    features: { hasOnlineOrdering: true, hasDelivery: true, acceptsOnlinePayment: true },
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date(),
  },
  {
    id: 'shop-002',
    mallId: MALL_CONFIG.DEFAULT_MALL_ID,
    name: 'Zara',
    nameAr: 'زارا',
    category: 'Fashion',
    iconUrl: 'https://example.com/icons/zara.png',
    websiteUrl: 'https://zara.com',
    description: 'Spanish fashion retailer offering trendy clothing for men, women, and children',
    location: { floor: '2', zone: 'B', unit: '201' },
    contact: { phone: '+966 11 222 2222', whatsapp: '+966 50 222 2222', email: 'zara@riyadhpark.com' },
    hours: mockMall.hours,
    rating: 4.3,
    isActive: true,
    subscription: { tier: 'professional', status: 'active' },
    features: { hasOnlineOrdering: true, hasDelivery: false, acceptsOnlinePayment: true },
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date(),
  },
  {
    id: 'shop-003',
    mallId: MALL_CONFIG.DEFAULT_MALL_ID,
    name: 'Apple Store',
    nameAr: 'متجر آبل',
    category: 'Electronics',
    iconUrl: 'https://example.com/icons/apple.png',
    websiteUrl: 'https://apple.com',
    description: 'Premium electronics and technology products',
    location: { floor: '1', zone: 'C', unit: '105' },
    contact: { phone: '+966 11 333 3333', whatsapp: '+966 50 333 3333', email: 'apple@riyadhpark.com' },
    hours: mockMall.hours,
    rating: 4.8,
    isActive: true,
    subscription: { tier: 'premium', status: 'active' },
    features: { hasOnlineOrdering: true, hasDelivery: true, acceptsOnlinePayment: true },
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date(),
  },
  {
    id: 'shop-004',
    mallId: MALL_CONFIG.DEFAULT_MALL_ID,
    name: 'KFC',
    nameAr: 'كنتاكي',
    category: 'Food & Dining',
    iconUrl: 'https://example.com/icons/kfc.png',
    websiteUrl: 'https://kfc.com',
    description: 'Fast food restaurant chain specializing in fried chicken',
    location: { floor: '3', zone: 'D', unit: '301' },
    contact: { phone: '+966 11 444 4444', whatsapp: '+966 50 444 4444', email: 'kfc@riyadhpark.com' },
    hours: mockMall.hours,
    rating: 4.2,
    isActive: true,
    subscription: { tier: 'basic', status: 'active' },
    features: { hasOnlineOrdering: true, hasDelivery: true, acceptsOnlinePayment: true },
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date(),
  },
  {
    id: 'shop-005',
    mallId: MALL_CONFIG.DEFAULT_MALL_ID,
    name: 'Sephora',
    nameAr: 'سيفورا',
    category: 'Beauty & Health',
    iconUrl: 'https://example.com/icons/sephora.png',
    websiteUrl: 'https://sephora.com',
    description: 'Beauty retailer offering cosmetics, skincare, and fragrance products',
    location: { floor: '2', zone: 'E', unit: '205' },
    contact: { phone: '+966 11 555 5555', whatsapp: '+966 50 555 5555', email: 'sephora@riyadhpark.com' },
    hours: mockMall.hours,
    rating: 4.6,
    isActive: true,
    subscription: { tier: 'professional', status: 'active' },
    features: { hasOnlineOrdering: true, hasDelivery: false, acceptsOnlinePayment: true },
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date(),
  },
];

export const mockOffers: Offer[] = [
  {
    id: 'offer-001',
    mallId: MALL_CONFIG.DEFAULT_MALL_ID,
    shopId: 'shop-001',
    title: 'Up to 50% Off Athletic Wear',
    description: 'Get up to 50% off on selected athletic wear and sneakers',
    imageUrl: 'https://example.com/offers/adidas-sale.jpg',
    validFrom: new Date('2024-01-01'),
    validUntil: new Date('2024-01-31'),
    discountPercentage: 50,
    isActive: true,
    isFeatured: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date(),
  },
  {
    id: 'offer-002',
    mallId: MALL_CONFIG.DEFAULT_MALL_ID,
    shopId: 'shop-002',
    title: 'New Season Collection',
    description: 'Discover the latest fashion trends for the new season',
    imageUrl: 'https://example.com/offers/zara-collection.jpg',
    validFrom: new Date('2024-01-01'),
    validUntil: new Date('2024-02-15'),
    isActive: true,
    isFeatured: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date(),
  },
  {
    id: 'offer-003',
    mallId: MALL_CONFIG.DEFAULT_MALL_ID,
    shopId: 'shop-004',
    title: 'Family Feast Deal',
    description: 'Family meal for 4 people at a special price',
    imageUrl: 'https://example.com/offers/kfc-family.jpg',
    validFrom: new Date('2024-01-01'),
    validUntil: new Date('2024-01-31'),
    originalPrice: 120,
    salePrice: 89,
    isActive: true,
    isFeatured: false,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date(),
  },
];