# Alertmanager Configuration
# Alert routing and notification configuration

global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@mallsystem.com'
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'default-receiver'
  routes:
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 1s
      repeat_interval: 5m
    - match:
        severity: warning
      receiver: 'warning-alerts'
      group_wait: 5s
      repeat_interval: 15m
    - match:
        alertname: 'HighErrorRate'
      receiver: 'error-alerts'
      group_wait: 1s
      repeat_interval: 2m
    - match:
        alertname: 'DatabaseDown'
      receiver: 'database-alerts'
      group_wait: 1s
      repeat_interval: 1m

receivers:
  - name: 'default-receiver'
    email_configs:
      - to: 'admin@mallsystem.com'
        subject: 'Mall System Alert: {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Labels: {{ .Labels }}
          {{ end }}
    webhook_configs:
      - url: 'http://api:3001/api/v1/webhooks/alerts'
        send_resolved: true

  - name: 'critical-alerts'
    email_configs:
      - to: 'admin@mallsystem.com'
        subject: '🚨 CRITICAL: Mall System Alert'
        body: |
          🚨 CRITICAL ALERT 🚨
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Labels: {{ .Labels }}
          Started: {{ .StartsAt }}
          {{ end }}
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
        channel: '#critical-alerts'
        color: 'danger'
        title: '🚨 Critical Mall System Alert'
        text: |
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          *Labels:* {{ .Labels }}
          {{ end }}

  - name: 'warning-alerts'
    email_configs:
      - to: 'team@mallsystem.com'
        subject: '⚠️ WARNING: Mall System Alert'
        body: |
          ⚠️ WARNING ALERT ⚠️
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Labels: {{ .Labels }}
          Started: {{ .StartsAt }}
          {{ end }}
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
        channel: '#alerts'
        color: 'warning'
        title: '⚠️ Mall System Warning'
        text: |
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          {{ end }}

  - name: 'error-alerts'
    email_configs:
      - to: 'developers@mallsystem.com'
        subject: '🐛 ERROR: High Error Rate Detected'
        body: |
          🐛 ERROR RATE ALERT 🐛
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Current Error Rate: {{ .Labels.error_rate }}%
          {{ end }}

  - name: 'database-alerts'
    email_configs:
      - to: 'dba@mallsystem.com'
        subject: '🗄️ DATABASE: Connection Issue'
        body: |
          🗄️ DATABASE ALERT 🗄️
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Database: {{ .Labels.database }}
          {{ end }}
    pagerduty_configs:
      - service_key: 'YOUR_PAGERDUTY_SERVICE_KEY'
        description: 'Mall System Database Alert'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']