# Prometheus Configuration
# Monitoring and alerting configuration for Mall Admin System

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'mall-admin-system'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  - "/etc/prometheus/rules/*.yml"

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Mall API Server
  - job_name: 'mall-api'
    static_configs:
      - targets: ['api:3001']
    metrics_path: '/api/v1/metrics'
    scrape_interval: 10s
    scrape_timeout: 10s
    params:
      format: ['prometheus']

  # Shop Admin Dashboard
  - job_name: 'shop-admin'
    static_configs:
      - targets: ['shop-admin:3000']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # PostgreSQL Database
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres_exporter:9187']
    scrape_interval: 10s

  # Redis Cache
  - job_name: 'redis'
    static_configs:
      - targets: ['redis_exporter:9121']
    scrape_interval: 10s

  # Nginx Reverse Proxy
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx_exporter:9113']
    scrape_interval: 10s

  # Node.js Application Metrics
  - job_name: 'node-app'
    static_configs:
      - targets: ['api:3001']
    metrics_path: '/api/v1/performance/metrics'
    scrape_interval: 5s
    scrape_timeout: 5s

  # System Metrics (Node Exporter)
  - job_name: 'system'
    static_configs:
      - targets: ['node_exporter:9100']
    scrape_interval: 10s

  # Docker Container Metrics
  - job_name: 'docker'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 10s

  # Application Health Checks
  - job_name: 'health-checks'
    static_configs:
      - targets: ['api:3001']
    metrics_path: '/api/v1/health'
    scrape_interval: 30s
    scrape_timeout: 10s
    params:
      format: ['prometheus']

  # Performance Monitoring
  - job_name: 'performance'
    static_configs:
      - targets: ['api:3001']
    metrics_path: '/api/v1/performance/stats'
    scrape_interval: 30s
    scrape_timeout: 10s
    params:
      format: ['prometheus']

# Remote write configuration for long-term storage
remote_write:
  - url: "http://victoriametrics:8428/api/v1/write"
    queue_config:
      max_samples_per_send: 1000
      max_shards: 200
      capacity: 2500

# Remote read configuration
remote_read:
  - url: "http://victoriametrics:8428/api/v1/read"
    read_recent: true